# Generated by Django 4.0 on 2021-12-24 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=400)),
                ('breed', models.CharField(max_length=30)),
                ('сontact_person', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=13)),
                ('locality', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='uploads')),
                ('issued', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.author')),
            ],
        ),
    ]
