# Generated by Django 4.0 on 2021-12-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pet_type',
            field=models.CharField(choices=[('c', 'cat'), ('d', 'dog')], default='c', max_length=1),
        ),
    ]
